task_mngr/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('task_mngr_app.urls')),
]

task_mngr_app/urls.py
from django.urls import path
from . import views
from .views import TaskView, TaskDetailView, TaskEditView

app_name = 'task_mngr_app'

urlpatterns = [
    path('', TaskView.as_view(), name="home"),
    path('details/<int:pk>', TaskDetailView.as_view(), name="details"),
    path('edit/<int:pk>', TaskEditView.as_view(), name='edit'),
    path('add/', views.task_add, name='add'),
    path('login/', views.user_login, name='login'),
    path('register/', views.register, name='register'),
]

task_mngr_app/models.py
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db import models


class State(models.Model):
    title = models.CharField(max_length=50, null=True, default=None)
    weight = models.IntegerField(default=0, validators=[MaxValueValidator(2), MinValueValidator(0)])
    color = models.CharField(max_length=50, null=True, blank=True)

    def __str__(self):
        return self.title


class Task(models.Model):
    working_person = models.CharField(max_length=30)
    creation_date = models.DateTimeField(auto_now_add=True)
    start_date = models.DateTimeField(null=True, blank=True)
    end_date = models.DateTimeField(null=True, blank=True)
    deadline = models.DateTimeField()
    state = models.ForeignKey(State, on_delete=models.CASCADE, null=True)
    title = models.CharField(max_length=100)
    content = models.TextField()
    files = models.FileField(upload_to='task_files/', null=True, blank=True)

    def __str__(self):
        return self.title

task_mngr_app/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import State, Task


class StateForm(forms.ModelForm):
    class Meta:
        model = State
        fields = ['title', 'weight', 'color']


class TaskForm(forms.ModelForm):
    delete_files = forms.BooleanField(required=False, initial=False, label='Delete Files')

    class Meta:
        model = Task
        fields = ['title', 'working_person', 'start_date', 'end_date', 'deadline', 'state', 'content', 'files']

        widgets = {
            'deadline': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'start_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
            'end_date': forms.DateTimeInput(attrs={'type': 'datetime-local'}),
        }


class LoginForm(forms.Form):
    username = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Username'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password'}))


class RegistrationForm(forms.ModelForm):
    username = forms.CharField(label='Username', widget=forms.TextInput(attrs={'placeholder': 'Enter username'}))
    password = forms.CharField(label='Password', widget=forms.PasswordInput(attrs={'placeholder': 'Enter password'}))
    password2 = forms.CharField(label='Repeat Password', widget=forms.PasswordInput(attrs={'placeholder': 'Repeat password'}))

    class Meta:
        model = User
        fields = ['username']

    def clean_password2(self):
        cleaned_data = super().clean()
        password = cleaned_data.get('password')
        password2 = cleaned_data.get('password2')

        if password and password2 and password != password2:
            raise forms.ValidationError("Passwords don't match.")

        return password2

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data["password"])
        if commit:
            user.save()
        return user

task_mngr_app/views.py
from django.contrib.auth import login, authenticate
from django.contrib.auth.models import User
from django.http import HttpResponseRedirect
from django.shortcuts import redirect, render
from django.views.generic import ListView, DetailView, CreateView, UpdateView

from .forms import LoginForm, TaskForm, RegistrationForm
from .models import Task




class TaskView(ListView):
    model = Task
    template_name = 'home.html'


class TaskDetailView(DetailView):
    model = Task
    template_name = 'details.html'


class TaskEditView(UpdateView):
    model = Task
    template_name = 'edit.html'
    fields = '__all__'

    def form_valid(self, form):
        task = form.save()
        return redirect('task_mngr_app:details', pk=task.pk)


# class TaskAddView(CreateView):
#    model = Task
#    template_name = 'add.html'
#    fields = '__all__'


# def form_valid(self, form):
#    task = form.save()
#    return redirect('task_mngr_app:details', pk=task.pk)


def task_add(request):
    if request.method == 'POST':
        form = TaskForm(request.POST)
        if form.is_valid():
            task = form.save()
            return redirect('task_mngr_app:details', pk=task.pk)
    else:
        form = TaskForm()

    return render(request, 'add.html', {'form': form})


def user_login(request):
    loginError = False
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            user = authenticate(username=cd['username'], password=cd['password'])

            if user is not None:
                if user.is_active:
                    login(request, user)
                    return HttpResponseRedirect('/')
            else:
                loginError = True
    else:
        form = LoginForm()

    return render(request, 'login.html', {'form': form, 'loginError': loginError})


def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = RegistrationForm()

    return render(request, 'register.html', {'form': form})

templates/add.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/edit-add.css' %}">
{% endblock %}

{% block content %}
    <main>
        <form method="post" class="edit_form">
            {% csrf_token %}
            {{ form.as_p }}

            <div class="edit_add">
                <input type="submit" value="Add">
                <a href=".." class="edit_cancel" style="color: #ff5858">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pl">
<head>
    <meta charset="UTF-8">
    <title>Title</title>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">

    <link rel="stylesheet" href="{% static "css/style.css" %}">
    {% block links %}{% endblock %}
</head>
<body>
    <nav>
        <a href=".." class="header-name-dda">T4SK5</a>
        <a href="/login/" class="logout">wyloguj</a>
    </nav>

    {% block content %}
    {% endblock %}

    <br>
</body>
</html>

templates/details.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/detail.css' %}">
{% endblock %}

{% block content %}
    <main>
        <div class="main-box">
            <div class="title_state">
                <div class="title"><h1>{{ task.title }}</h1></div>
            </div>

            <div class="dates">
                <div class="working_person">Working person: <b>{{ task.working_person }}</b></div>
                <div class="state_detail" >Stan: <b style="color: {{ task.state.color }};"> {{ task.state.title }}</b></div>
                <div class="creation_date">Created: <b>{{ task.creation_date }}</b></div>
                <div class="taken_date">Przyjęte: <b>{{ task.start_date }}</b></div>
                <div class="taken_date">Zakończone: <b>{{ task.end_date }}</b></div>
                <div class="deadline">Deadline: <b>{{ task.deadline }}</b></div>
                <div class="text"><b>{{ task.content }}</b></div>
                <div class="text">Załączone pliki: <a href="{{ task.files }}" download> Pobierz plik </a></div>

                <div class="add">
                    <a href="/edit/{{ task.id }}" >Edit</a>
                    <a href=".." class="cancel" style="color: #ff5858">Back</a>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

templates/edit.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/edit-add.css' %}">
{% endblock %}

{% block content %}
    <main>
        <form method="post" class="edit_form" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.media }}
            {{ form.as_p }}
            <div class="form-group">
                <label for="id_delete_files">{{ form.delete_files.label }}</label>
                {{ form.delete_files }}
            </div>
            <script>
                document.getElementById("id_start_date").type = "datetime-local";
                document.getElementById("id_end_date").type = "datetime-local";
                document.getElementById("id_deadline").type = "datetime-local";
            </script>
            <div class="edit_buttons">
                <button>Save</button>
                <a href="/details/{{ task.id }}" class="edit_cancel" style="color: #ff5858">Back</a>
            </div>
        </form>
    </main>
{% endblock %}

templates/home.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}">
{% endblock %}

{% block content %}
    <br><br>
    <div class="row">
        {% for task in object_list %}
            <br>
            <a href="/details/{{ task.id }}" class="task col-12 col-md-4 col-lg-4 shadow-1">
                <div class="task">
                    <h1 class="task_name">{{ task.title }}</h1>
                    <div class="task_creation_date">{{ task.creation_date|date:"Y-m-d" }}</div>
                    <div class="task_working_person">{{ task.working_person }}</div>
                    <div class="task_state" style="color: {{ task.state.color }};">{{ task.state.title }}</div>
                    <div class="task_deadline">Deadline: {{task.deadline}}</div>
                </div>
            </a>
        {% endfor %}
    </div>
    <br>
    <hr><br>
    <a href="/add" class="task">
        <div class="add-button">
            <i class="bi bi-plus-circle-fill"></i>
            <div class="task_add">Add note</div>
        </div>
    </a>
{% endblock %}

<!--{}

templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/user-login.css' %}">
{% endblock %}

{% block content %}
    <main>
        <form method="post" class="edit_form">
            {% csrf_token %}
            <h1>Zaloguj się</h1>
            {{ form.as_p }}
            <div class="log_in">

                {% if loginError %}
            	    <center style="color: #f00;"> Niepoprawny login</center>
                    <br>
                {% endif %}

                <input type="submit" value="Log In">
            </div>
            <a href="/register/">SIGN UP</a>
        </form>
    </main>
{% endblock %}

templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block links %}
    <link rel="stylesheet" href="{% static 'css/user-login.css' %}">
{% endblock %}

{% block content %}
    <main>
        <h1>Create your account</h1>
        <br>
        <form method="post">
            {% csrf_token %}
            {{ form.username }}
            {{ form.password }}
            {{ form.password2 }}
            <input type="submit" value="Create">
            <a href="/login/" class="register_cancel" style="color: #ff5858">Back</a>
        </form>
    </main>
{% endblock %}